// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: vlm/v1/worker.proto

#include "vlm/v1/worker.pb.h"
#include "vlm/v1/worker.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace vlm {
namespace v1 {

static const char* VisionService_method_names[] = {
  "/vlm.v1.VisionService/Encode",
  "/vlm.v1.VisionService/EncodeThenGenerate",
  "/vlm.v1.VisionService/Health",
};

std::unique_ptr< VisionService::Stub> VisionService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< VisionService::Stub> stub(new VisionService::Stub(channel));
  return stub;
}

VisionService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Encode_(VisionService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_EncodeThenGenerate_(VisionService_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Health_(VisionService_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status VisionService::Stub::Encode(::grpc::ClientContext* context, const ::vlm::v1::EncodeRequest& request, ::vlm::v1::EncodeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Encode_, context, request, response);
}

void VisionService::Stub::experimental_async::Encode(::grpc::ClientContext* context, const ::vlm::v1::EncodeRequest* request, ::vlm::v1::EncodeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Encode_, context, request, response, std::move(f));
}

void VisionService::Stub::experimental_async::Encode(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::EncodeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Encode_, context, request, response, std::move(f));
}

void VisionService::Stub::experimental_async::Encode(::grpc::ClientContext* context, const ::vlm::v1::EncodeRequest* request, ::vlm::v1::EncodeResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Encode_, context, request, response, reactor);
}

void VisionService::Stub::experimental_async::Encode(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::EncodeResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Encode_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vlm::v1::EncodeResponse>* VisionService::Stub::AsyncEncodeRaw(::grpc::ClientContext* context, const ::vlm::v1::EncodeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::vlm::v1::EncodeResponse>::Create(channel_.get(), cq, rpcmethod_Encode_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::vlm::v1::EncodeResponse>* VisionService::Stub::PrepareAsyncEncodeRaw(::grpc::ClientContext* context, const ::vlm::v1::EncodeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::vlm::v1::EncodeResponse>::Create(channel_.get(), cq, rpcmethod_Encode_, context, request, false);
}

::grpc::Status VisionService::Stub::EncodeThenGenerate(::grpc::ClientContext* context, const ::vlm::v1::EncodeThenGenerateRequest& request, ::vlm::v1::EncodeThenGenerateResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_EncodeThenGenerate_, context, request, response);
}

void VisionService::Stub::experimental_async::EncodeThenGenerate(::grpc::ClientContext* context, const ::vlm::v1::EncodeThenGenerateRequest* request, ::vlm::v1::EncodeThenGenerateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_EncodeThenGenerate_, context, request, response, std::move(f));
}

void VisionService::Stub::experimental_async::EncodeThenGenerate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::EncodeThenGenerateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_EncodeThenGenerate_, context, request, response, std::move(f));
}

void VisionService::Stub::experimental_async::EncodeThenGenerate(::grpc::ClientContext* context, const ::vlm::v1::EncodeThenGenerateRequest* request, ::vlm::v1::EncodeThenGenerateResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_EncodeThenGenerate_, context, request, response, reactor);
}

void VisionService::Stub::experimental_async::EncodeThenGenerate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::EncodeThenGenerateResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_EncodeThenGenerate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vlm::v1::EncodeThenGenerateResponse>* VisionService::Stub::AsyncEncodeThenGenerateRaw(::grpc::ClientContext* context, const ::vlm::v1::EncodeThenGenerateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::vlm::v1::EncodeThenGenerateResponse>::Create(channel_.get(), cq, rpcmethod_EncodeThenGenerate_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::vlm::v1::EncodeThenGenerateResponse>* VisionService::Stub::PrepareAsyncEncodeThenGenerateRaw(::grpc::ClientContext* context, const ::vlm::v1::EncodeThenGenerateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::vlm::v1::EncodeThenGenerateResponse>::Create(channel_.get(), cq, rpcmethod_EncodeThenGenerate_, context, request, false);
}

::grpc::Status VisionService::Stub::Health(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest& request, ::vlm::v1::HealthResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Health_, context, request, response);
}

void VisionService::Stub::experimental_async::Health(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest* request, ::vlm::v1::HealthResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Health_, context, request, response, std::move(f));
}

void VisionService::Stub::experimental_async::Health(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::HealthResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Health_, context, request, response, std::move(f));
}

void VisionService::Stub::experimental_async::Health(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest* request, ::vlm::v1::HealthResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Health_, context, request, response, reactor);
}

void VisionService::Stub::experimental_async::Health(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::HealthResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Health_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vlm::v1::HealthResponse>* VisionService::Stub::AsyncHealthRaw(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::vlm::v1::HealthResponse>::Create(channel_.get(), cq, rpcmethod_Health_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::vlm::v1::HealthResponse>* VisionService::Stub::PrepareAsyncHealthRaw(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::vlm::v1::HealthResponse>::Create(channel_.get(), cq, rpcmethod_Health_, context, request, false);
}

VisionService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VisionService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VisionService::Service, ::vlm::v1::EncodeRequest, ::vlm::v1::EncodeResponse>(
          [](VisionService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::vlm::v1::EncodeRequest* req,
             ::vlm::v1::EncodeResponse* resp) {
               return service->Encode(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VisionService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VisionService::Service, ::vlm::v1::EncodeThenGenerateRequest, ::vlm::v1::EncodeThenGenerateResponse>(
          [](VisionService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::vlm::v1::EncodeThenGenerateRequest* req,
             ::vlm::v1::EncodeThenGenerateResponse* resp) {
               return service->EncodeThenGenerate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VisionService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VisionService::Service, ::vlm::v1::HealthRequest, ::vlm::v1::HealthResponse>(
          [](VisionService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::vlm::v1::HealthRequest* req,
             ::vlm::v1::HealthResponse* resp) {
               return service->Health(ctx, req, resp);
             }, this)));
}

VisionService::Service::~Service() {
}

::grpc::Status VisionService::Service::Encode(::grpc::ServerContext* context, const ::vlm::v1::EncodeRequest* request, ::vlm::v1::EncodeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VisionService::Service::EncodeThenGenerate(::grpc::ServerContext* context, const ::vlm::v1::EncodeThenGenerateRequest* request, ::vlm::v1::EncodeThenGenerateResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VisionService::Service::Health(::grpc::ServerContext* context, const ::vlm::v1::HealthRequest* request, ::vlm::v1::HealthResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* LlmService_method_names[] = {
  "/vlm.v1.LlmService/Generate",
  "/vlm.v1.LlmService/Health",
};

std::unique_ptr< LlmService::Stub> LlmService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< LlmService::Stub> stub(new LlmService::Stub(channel));
  return stub;
}

LlmService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Generate_(LlmService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Health_(LlmService_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status LlmService::Stub::Generate(::grpc::ClientContext* context, const ::vlm::v1::GenerateRequest& request, ::vlm::v1::GenerateResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Generate_, context, request, response);
}

void LlmService::Stub::experimental_async::Generate(::grpc::ClientContext* context, const ::vlm::v1::GenerateRequest* request, ::vlm::v1::GenerateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Generate_, context, request, response, std::move(f));
}

void LlmService::Stub::experimental_async::Generate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::GenerateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Generate_, context, request, response, std::move(f));
}

void LlmService::Stub::experimental_async::Generate(::grpc::ClientContext* context, const ::vlm::v1::GenerateRequest* request, ::vlm::v1::GenerateResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Generate_, context, request, response, reactor);
}

void LlmService::Stub::experimental_async::Generate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::GenerateResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Generate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vlm::v1::GenerateResponse>* LlmService::Stub::AsyncGenerateRaw(::grpc::ClientContext* context, const ::vlm::v1::GenerateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::vlm::v1::GenerateResponse>::Create(channel_.get(), cq, rpcmethod_Generate_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::vlm::v1::GenerateResponse>* LlmService::Stub::PrepareAsyncGenerateRaw(::grpc::ClientContext* context, const ::vlm::v1::GenerateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::vlm::v1::GenerateResponse>::Create(channel_.get(), cq, rpcmethod_Generate_, context, request, false);
}

::grpc::Status LlmService::Stub::Health(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest& request, ::vlm::v1::HealthResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Health_, context, request, response);
}

void LlmService::Stub::experimental_async::Health(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest* request, ::vlm::v1::HealthResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Health_, context, request, response, std::move(f));
}

void LlmService::Stub::experimental_async::Health(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::HealthResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Health_, context, request, response, std::move(f));
}

void LlmService::Stub::experimental_async::Health(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest* request, ::vlm::v1::HealthResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Health_, context, request, response, reactor);
}

void LlmService::Stub::experimental_async::Health(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::HealthResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Health_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vlm::v1::HealthResponse>* LlmService::Stub::AsyncHealthRaw(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::vlm::v1::HealthResponse>::Create(channel_.get(), cq, rpcmethod_Health_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::vlm::v1::HealthResponse>* LlmService::Stub::PrepareAsyncHealthRaw(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::vlm::v1::HealthResponse>::Create(channel_.get(), cq, rpcmethod_Health_, context, request, false);
}

LlmService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LlmService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LlmService::Service, ::vlm::v1::GenerateRequest, ::vlm::v1::GenerateResponse>(
          [](LlmService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::vlm::v1::GenerateRequest* req,
             ::vlm::v1::GenerateResponse* resp) {
               return service->Generate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LlmService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LlmService::Service, ::vlm::v1::HealthRequest, ::vlm::v1::HealthResponse>(
          [](LlmService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::vlm::v1::HealthRequest* req,
             ::vlm::v1::HealthResponse* resp) {
               return service->Health(ctx, req, resp);
             }, this)));
}

LlmService::Service::~Service() {
}

::grpc::Status LlmService::Service::Generate(::grpc::ServerContext* context, const ::vlm::v1::GenerateRequest* request, ::vlm::v1::GenerateResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LlmService::Service::Health(::grpc::ServerContext* context, const ::vlm::v1::HealthRequest* request, ::vlm::v1::HealthResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace vlm
}  // namespace v1

