// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: vlm/v1/worker.proto
#ifndef GRPC_vlm_2fv1_2fworker_2eproto__INCLUDED
#define GRPC_vlm_2fv1_2fworker_2eproto__INCLUDED

#include "vlm/v1/worker.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace vlm {
namespace v1 {

class VisionService final {
 public:
  static constexpr char const* service_full_name() {
    return "vlm.v1.VisionService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Encode(::grpc::ClientContext* context, const ::vlm::v1::EncodeRequest& request, ::vlm::v1::EncodeResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vlm::v1::EncodeResponse>> AsyncEncode(::grpc::ClientContext* context, const ::vlm::v1::EncodeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vlm::v1::EncodeResponse>>(AsyncEncodeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vlm::v1::EncodeResponse>> PrepareAsyncEncode(::grpc::ClientContext* context, const ::vlm::v1::EncodeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vlm::v1::EncodeResponse>>(PrepareAsyncEncodeRaw(context, request, cq));
    }
    virtual ::grpc::Status EncodeThenGenerate(::grpc::ClientContext* context, const ::vlm::v1::EncodeThenGenerateRequest& request, ::vlm::v1::EncodeThenGenerateResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vlm::v1::EncodeThenGenerateResponse>> AsyncEncodeThenGenerate(::grpc::ClientContext* context, const ::vlm::v1::EncodeThenGenerateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vlm::v1::EncodeThenGenerateResponse>>(AsyncEncodeThenGenerateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vlm::v1::EncodeThenGenerateResponse>> PrepareAsyncEncodeThenGenerate(::grpc::ClientContext* context, const ::vlm::v1::EncodeThenGenerateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vlm::v1::EncodeThenGenerateResponse>>(PrepareAsyncEncodeThenGenerateRaw(context, request, cq));
    }
    virtual ::grpc::Status Health(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest& request, ::vlm::v1::HealthResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vlm::v1::HealthResponse>> AsyncHealth(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vlm::v1::HealthResponse>>(AsyncHealthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vlm::v1::HealthResponse>> PrepareAsyncHealth(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vlm::v1::HealthResponse>>(PrepareAsyncHealthRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void Encode(::grpc::ClientContext* context, const ::vlm::v1::EncodeRequest* request, ::vlm::v1::EncodeResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Encode(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::EncodeResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Encode(::grpc::ClientContext* context, const ::vlm::v1::EncodeRequest* request, ::vlm::v1::EncodeResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Encode(::grpc::ClientContext* context, const ::vlm::v1::EncodeRequest* request, ::vlm::v1::EncodeResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Encode(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::EncodeResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Encode(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::EncodeResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void EncodeThenGenerate(::grpc::ClientContext* context, const ::vlm::v1::EncodeThenGenerateRequest* request, ::vlm::v1::EncodeThenGenerateResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void EncodeThenGenerate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::EncodeThenGenerateResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void EncodeThenGenerate(::grpc::ClientContext* context, const ::vlm::v1::EncodeThenGenerateRequest* request, ::vlm::v1::EncodeThenGenerateResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void EncodeThenGenerate(::grpc::ClientContext* context, const ::vlm::v1::EncodeThenGenerateRequest* request, ::vlm::v1::EncodeThenGenerateResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void EncodeThenGenerate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::EncodeThenGenerateResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void EncodeThenGenerate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::EncodeThenGenerateResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void Health(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest* request, ::vlm::v1::HealthResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Health(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::HealthResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Health(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest* request, ::vlm::v1::HealthResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Health(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest* request, ::vlm::v1::HealthResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Health(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::HealthResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Health(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::HealthResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vlm::v1::EncodeResponse>* AsyncEncodeRaw(::grpc::ClientContext* context, const ::vlm::v1::EncodeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vlm::v1::EncodeResponse>* PrepareAsyncEncodeRaw(::grpc::ClientContext* context, const ::vlm::v1::EncodeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vlm::v1::EncodeThenGenerateResponse>* AsyncEncodeThenGenerateRaw(::grpc::ClientContext* context, const ::vlm::v1::EncodeThenGenerateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vlm::v1::EncodeThenGenerateResponse>* PrepareAsyncEncodeThenGenerateRaw(::grpc::ClientContext* context, const ::vlm::v1::EncodeThenGenerateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vlm::v1::HealthResponse>* AsyncHealthRaw(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vlm::v1::HealthResponse>* PrepareAsyncHealthRaw(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Encode(::grpc::ClientContext* context, const ::vlm::v1::EncodeRequest& request, ::vlm::v1::EncodeResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vlm::v1::EncodeResponse>> AsyncEncode(::grpc::ClientContext* context, const ::vlm::v1::EncodeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vlm::v1::EncodeResponse>>(AsyncEncodeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vlm::v1::EncodeResponse>> PrepareAsyncEncode(::grpc::ClientContext* context, const ::vlm::v1::EncodeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vlm::v1::EncodeResponse>>(PrepareAsyncEncodeRaw(context, request, cq));
    }
    ::grpc::Status EncodeThenGenerate(::grpc::ClientContext* context, const ::vlm::v1::EncodeThenGenerateRequest& request, ::vlm::v1::EncodeThenGenerateResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vlm::v1::EncodeThenGenerateResponse>> AsyncEncodeThenGenerate(::grpc::ClientContext* context, const ::vlm::v1::EncodeThenGenerateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vlm::v1::EncodeThenGenerateResponse>>(AsyncEncodeThenGenerateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vlm::v1::EncodeThenGenerateResponse>> PrepareAsyncEncodeThenGenerate(::grpc::ClientContext* context, const ::vlm::v1::EncodeThenGenerateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vlm::v1::EncodeThenGenerateResponse>>(PrepareAsyncEncodeThenGenerateRaw(context, request, cq));
    }
    ::grpc::Status Health(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest& request, ::vlm::v1::HealthResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vlm::v1::HealthResponse>> AsyncHealth(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vlm::v1::HealthResponse>>(AsyncHealthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vlm::v1::HealthResponse>> PrepareAsyncHealth(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vlm::v1::HealthResponse>>(PrepareAsyncHealthRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Encode(::grpc::ClientContext* context, const ::vlm::v1::EncodeRequest* request, ::vlm::v1::EncodeResponse* response, std::function<void(::grpc::Status)>) override;
      void Encode(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::EncodeResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Encode(::grpc::ClientContext* context, const ::vlm::v1::EncodeRequest* request, ::vlm::v1::EncodeResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Encode(::grpc::ClientContext* context, const ::vlm::v1::EncodeRequest* request, ::vlm::v1::EncodeResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Encode(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::EncodeResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Encode(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::EncodeResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void EncodeThenGenerate(::grpc::ClientContext* context, const ::vlm::v1::EncodeThenGenerateRequest* request, ::vlm::v1::EncodeThenGenerateResponse* response, std::function<void(::grpc::Status)>) override;
      void EncodeThenGenerate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::EncodeThenGenerateResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void EncodeThenGenerate(::grpc::ClientContext* context, const ::vlm::v1::EncodeThenGenerateRequest* request, ::vlm::v1::EncodeThenGenerateResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void EncodeThenGenerate(::grpc::ClientContext* context, const ::vlm::v1::EncodeThenGenerateRequest* request, ::vlm::v1::EncodeThenGenerateResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void EncodeThenGenerate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::EncodeThenGenerateResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void EncodeThenGenerate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::EncodeThenGenerateResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void Health(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest* request, ::vlm::v1::HealthResponse* response, std::function<void(::grpc::Status)>) override;
      void Health(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::HealthResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Health(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest* request, ::vlm::v1::HealthResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Health(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest* request, ::vlm::v1::HealthResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Health(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::HealthResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Health(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::HealthResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::vlm::v1::EncodeResponse>* AsyncEncodeRaw(::grpc::ClientContext* context, const ::vlm::v1::EncodeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vlm::v1::EncodeResponse>* PrepareAsyncEncodeRaw(::grpc::ClientContext* context, const ::vlm::v1::EncodeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vlm::v1::EncodeThenGenerateResponse>* AsyncEncodeThenGenerateRaw(::grpc::ClientContext* context, const ::vlm::v1::EncodeThenGenerateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vlm::v1::EncodeThenGenerateResponse>* PrepareAsyncEncodeThenGenerateRaw(::grpc::ClientContext* context, const ::vlm::v1::EncodeThenGenerateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vlm::v1::HealthResponse>* AsyncHealthRaw(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vlm::v1::HealthResponse>* PrepareAsyncHealthRaw(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Encode_;
    const ::grpc::internal::RpcMethod rpcmethod_EncodeThenGenerate_;
    const ::grpc::internal::RpcMethod rpcmethod_Health_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Encode(::grpc::ServerContext* context, const ::vlm::v1::EncodeRequest* request, ::vlm::v1::EncodeResponse* response);
    virtual ::grpc::Status EncodeThenGenerate(::grpc::ServerContext* context, const ::vlm::v1::EncodeThenGenerateRequest* request, ::vlm::v1::EncodeThenGenerateResponse* response);
    virtual ::grpc::Status Health(::grpc::ServerContext* context, const ::vlm::v1::HealthRequest* request, ::vlm::v1::HealthResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Encode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Encode() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Encode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Encode(::grpc::ServerContext* /*context*/, const ::vlm::v1::EncodeRequest* /*request*/, ::vlm::v1::EncodeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEncode(::grpc::ServerContext* context, ::vlm::v1::EncodeRequest* request, ::grpc::ServerAsyncResponseWriter< ::vlm::v1::EncodeResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_EncodeThenGenerate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_EncodeThenGenerate() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_EncodeThenGenerate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EncodeThenGenerate(::grpc::ServerContext* /*context*/, const ::vlm::v1::EncodeThenGenerateRequest* /*request*/, ::vlm::v1::EncodeThenGenerateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEncodeThenGenerate(::grpc::ServerContext* context, ::vlm::v1::EncodeThenGenerateRequest* request, ::grpc::ServerAsyncResponseWriter< ::vlm::v1::EncodeThenGenerateResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Health() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::vlm::v1::HealthRequest* /*request*/, ::vlm::v1::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHealth(::grpc::ServerContext* context, ::vlm::v1::HealthRequest* request, ::grpc::ServerAsyncResponseWriter< ::vlm::v1::HealthResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Encode<WithAsyncMethod_EncodeThenGenerate<WithAsyncMethod_Health<Service > > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Encode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Encode() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::vlm::v1::EncodeRequest, ::vlm::v1::EncodeResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::vlm::v1::EncodeRequest* request, ::vlm::v1::EncodeResponse* response) { return this->Encode(context, request, response); }));}
    void SetMessageAllocatorFor_Encode(
        ::grpc::experimental::MessageAllocator< ::vlm::v1::EncodeRequest, ::vlm::v1::EncodeResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::vlm::v1::EncodeRequest, ::vlm::v1::EncodeResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Encode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Encode(::grpc::ServerContext* /*context*/, const ::vlm::v1::EncodeRequest* /*request*/, ::vlm::v1::EncodeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Encode(
      ::grpc::CallbackServerContext* /*context*/, const ::vlm::v1::EncodeRequest* /*request*/, ::vlm::v1::EncodeResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Encode(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::vlm::v1::EncodeRequest* /*request*/, ::vlm::v1::EncodeResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_EncodeThenGenerate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_EncodeThenGenerate() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::vlm::v1::EncodeThenGenerateRequest, ::vlm::v1::EncodeThenGenerateResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::vlm::v1::EncodeThenGenerateRequest* request, ::vlm::v1::EncodeThenGenerateResponse* response) { return this->EncodeThenGenerate(context, request, response); }));}
    void SetMessageAllocatorFor_EncodeThenGenerate(
        ::grpc::experimental::MessageAllocator< ::vlm::v1::EncodeThenGenerateRequest, ::vlm::v1::EncodeThenGenerateResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::vlm::v1::EncodeThenGenerateRequest, ::vlm::v1::EncodeThenGenerateResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_EncodeThenGenerate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EncodeThenGenerate(::grpc::ServerContext* /*context*/, const ::vlm::v1::EncodeThenGenerateRequest* /*request*/, ::vlm::v1::EncodeThenGenerateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* EncodeThenGenerate(
      ::grpc::CallbackServerContext* /*context*/, const ::vlm::v1::EncodeThenGenerateRequest* /*request*/, ::vlm::v1::EncodeThenGenerateResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* EncodeThenGenerate(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::vlm::v1::EncodeThenGenerateRequest* /*request*/, ::vlm::v1::EncodeThenGenerateResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Health() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(2,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::vlm::v1::HealthRequest, ::vlm::v1::HealthResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::vlm::v1::HealthRequest* request, ::vlm::v1::HealthResponse* response) { return this->Health(context, request, response); }));}
    void SetMessageAllocatorFor_Health(
        ::grpc::experimental::MessageAllocator< ::vlm::v1::HealthRequest, ::vlm::v1::HealthResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(2);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::vlm::v1::HealthRequest, ::vlm::v1::HealthResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::vlm::v1::HealthRequest* /*request*/, ::vlm::v1::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Health(
      ::grpc::CallbackServerContext* /*context*/, const ::vlm::v1::HealthRequest* /*request*/, ::vlm::v1::HealthResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Health(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::vlm::v1::HealthRequest* /*request*/, ::vlm::v1::HealthResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_Encode<ExperimentalWithCallbackMethod_EncodeThenGenerate<ExperimentalWithCallbackMethod_Health<Service > > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_Encode<ExperimentalWithCallbackMethod_EncodeThenGenerate<ExperimentalWithCallbackMethod_Health<Service > > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Encode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Encode() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Encode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Encode(::grpc::ServerContext* /*context*/, const ::vlm::v1::EncodeRequest* /*request*/, ::vlm::v1::EncodeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_EncodeThenGenerate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_EncodeThenGenerate() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_EncodeThenGenerate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EncodeThenGenerate(::grpc::ServerContext* /*context*/, const ::vlm::v1::EncodeThenGenerateRequest* /*request*/, ::vlm::v1::EncodeThenGenerateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Health() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::vlm::v1::HealthRequest* /*request*/, ::vlm::v1::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Encode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Encode() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Encode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Encode(::grpc::ServerContext* /*context*/, const ::vlm::v1::EncodeRequest* /*request*/, ::vlm::v1::EncodeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEncode(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_EncodeThenGenerate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_EncodeThenGenerate() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_EncodeThenGenerate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EncodeThenGenerate(::grpc::ServerContext* /*context*/, const ::vlm::v1::EncodeThenGenerateRequest* /*request*/, ::vlm::v1::EncodeThenGenerateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEncodeThenGenerate(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Health() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::vlm::v1::HealthRequest* /*request*/, ::vlm::v1::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHealth(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Encode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Encode() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Encode(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Encode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Encode(::grpc::ServerContext* /*context*/, const ::vlm::v1::EncodeRequest* /*request*/, ::vlm::v1::EncodeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Encode(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Encode(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_EncodeThenGenerate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_EncodeThenGenerate() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->EncodeThenGenerate(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_EncodeThenGenerate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EncodeThenGenerate(::grpc::ServerContext* /*context*/, const ::vlm::v1::EncodeThenGenerateRequest* /*request*/, ::vlm::v1::EncodeThenGenerateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* EncodeThenGenerate(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* EncodeThenGenerate(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Health() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(2,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Health(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::vlm::v1::HealthRequest* /*request*/, ::vlm::v1::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Health(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Health(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Encode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Encode() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::vlm::v1::EncodeRequest, ::vlm::v1::EncodeResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::vlm::v1::EncodeRequest, ::vlm::v1::EncodeResponse>* streamer) {
                       return this->StreamedEncode(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Encode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Encode(::grpc::ServerContext* /*context*/, const ::vlm::v1::EncodeRequest* /*request*/, ::vlm::v1::EncodeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedEncode(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vlm::v1::EncodeRequest,::vlm::v1::EncodeResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_EncodeThenGenerate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_EncodeThenGenerate() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::vlm::v1::EncodeThenGenerateRequest, ::vlm::v1::EncodeThenGenerateResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::vlm::v1::EncodeThenGenerateRequest, ::vlm::v1::EncodeThenGenerateResponse>* streamer) {
                       return this->StreamedEncodeThenGenerate(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_EncodeThenGenerate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status EncodeThenGenerate(::grpc::ServerContext* /*context*/, const ::vlm::v1::EncodeThenGenerateRequest* /*request*/, ::vlm::v1::EncodeThenGenerateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedEncodeThenGenerate(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vlm::v1::EncodeThenGenerateRequest,::vlm::v1::EncodeThenGenerateResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Health() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::vlm::v1::HealthRequest, ::vlm::v1::HealthResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::vlm::v1::HealthRequest, ::vlm::v1::HealthResponse>* streamer) {
                       return this->StreamedHealth(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::vlm::v1::HealthRequest* /*request*/, ::vlm::v1::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedHealth(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vlm::v1::HealthRequest,::vlm::v1::HealthResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Encode<WithStreamedUnaryMethod_EncodeThenGenerate<WithStreamedUnaryMethod_Health<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Encode<WithStreamedUnaryMethod_EncodeThenGenerate<WithStreamedUnaryMethod_Health<Service > > > StreamedService;
};

class LlmService final {
 public:
  static constexpr char const* service_full_name() {
    return "vlm.v1.LlmService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Generate(::grpc::ClientContext* context, const ::vlm::v1::GenerateRequest& request, ::vlm::v1::GenerateResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vlm::v1::GenerateResponse>> AsyncGenerate(::grpc::ClientContext* context, const ::vlm::v1::GenerateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vlm::v1::GenerateResponse>>(AsyncGenerateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vlm::v1::GenerateResponse>> PrepareAsyncGenerate(::grpc::ClientContext* context, const ::vlm::v1::GenerateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vlm::v1::GenerateResponse>>(PrepareAsyncGenerateRaw(context, request, cq));
    }
    virtual ::grpc::Status Health(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest& request, ::vlm::v1::HealthResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vlm::v1::HealthResponse>> AsyncHealth(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vlm::v1::HealthResponse>>(AsyncHealthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vlm::v1::HealthResponse>> PrepareAsyncHealth(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vlm::v1::HealthResponse>>(PrepareAsyncHealthRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void Generate(::grpc::ClientContext* context, const ::vlm::v1::GenerateRequest* request, ::vlm::v1::GenerateResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Generate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::GenerateResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Generate(::grpc::ClientContext* context, const ::vlm::v1::GenerateRequest* request, ::vlm::v1::GenerateResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Generate(::grpc::ClientContext* context, const ::vlm::v1::GenerateRequest* request, ::vlm::v1::GenerateResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Generate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::GenerateResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Generate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::GenerateResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void Health(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest* request, ::vlm::v1::HealthResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Health(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::HealthResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Health(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest* request, ::vlm::v1::HealthResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Health(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest* request, ::vlm::v1::HealthResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Health(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::HealthResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Health(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::HealthResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vlm::v1::GenerateResponse>* AsyncGenerateRaw(::grpc::ClientContext* context, const ::vlm::v1::GenerateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vlm::v1::GenerateResponse>* PrepareAsyncGenerateRaw(::grpc::ClientContext* context, const ::vlm::v1::GenerateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vlm::v1::HealthResponse>* AsyncHealthRaw(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vlm::v1::HealthResponse>* PrepareAsyncHealthRaw(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Generate(::grpc::ClientContext* context, const ::vlm::v1::GenerateRequest& request, ::vlm::v1::GenerateResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vlm::v1::GenerateResponse>> AsyncGenerate(::grpc::ClientContext* context, const ::vlm::v1::GenerateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vlm::v1::GenerateResponse>>(AsyncGenerateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vlm::v1::GenerateResponse>> PrepareAsyncGenerate(::grpc::ClientContext* context, const ::vlm::v1::GenerateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vlm::v1::GenerateResponse>>(PrepareAsyncGenerateRaw(context, request, cq));
    }
    ::grpc::Status Health(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest& request, ::vlm::v1::HealthResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vlm::v1::HealthResponse>> AsyncHealth(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vlm::v1::HealthResponse>>(AsyncHealthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vlm::v1::HealthResponse>> PrepareAsyncHealth(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vlm::v1::HealthResponse>>(PrepareAsyncHealthRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Generate(::grpc::ClientContext* context, const ::vlm::v1::GenerateRequest* request, ::vlm::v1::GenerateResponse* response, std::function<void(::grpc::Status)>) override;
      void Generate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::GenerateResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Generate(::grpc::ClientContext* context, const ::vlm::v1::GenerateRequest* request, ::vlm::v1::GenerateResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Generate(::grpc::ClientContext* context, const ::vlm::v1::GenerateRequest* request, ::vlm::v1::GenerateResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Generate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::GenerateResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Generate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::GenerateResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void Health(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest* request, ::vlm::v1::HealthResponse* response, std::function<void(::grpc::Status)>) override;
      void Health(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::HealthResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Health(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest* request, ::vlm::v1::HealthResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Health(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest* request, ::vlm::v1::HealthResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Health(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::HealthResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Health(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vlm::v1::HealthResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::vlm::v1::GenerateResponse>* AsyncGenerateRaw(::grpc::ClientContext* context, const ::vlm::v1::GenerateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vlm::v1::GenerateResponse>* PrepareAsyncGenerateRaw(::grpc::ClientContext* context, const ::vlm::v1::GenerateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vlm::v1::HealthResponse>* AsyncHealthRaw(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vlm::v1::HealthResponse>* PrepareAsyncHealthRaw(::grpc::ClientContext* context, const ::vlm::v1::HealthRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Generate_;
    const ::grpc::internal::RpcMethod rpcmethod_Health_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Generate(::grpc::ServerContext* context, const ::vlm::v1::GenerateRequest* request, ::vlm::v1::GenerateResponse* response);
    virtual ::grpc::Status Health(::grpc::ServerContext* context, const ::vlm::v1::HealthRequest* request, ::vlm::v1::HealthResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Generate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Generate() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Generate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Generate(::grpc::ServerContext* /*context*/, const ::vlm::v1::GenerateRequest* /*request*/, ::vlm::v1::GenerateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGenerate(::grpc::ServerContext* context, ::vlm::v1::GenerateRequest* request, ::grpc::ServerAsyncResponseWriter< ::vlm::v1::GenerateResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Health() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::vlm::v1::HealthRequest* /*request*/, ::vlm::v1::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHealth(::grpc::ServerContext* context, ::vlm::v1::HealthRequest* request, ::grpc::ServerAsyncResponseWriter< ::vlm::v1::HealthResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Generate<WithAsyncMethod_Health<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Generate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Generate() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::vlm::v1::GenerateRequest, ::vlm::v1::GenerateResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::vlm::v1::GenerateRequest* request, ::vlm::v1::GenerateResponse* response) { return this->Generate(context, request, response); }));}
    void SetMessageAllocatorFor_Generate(
        ::grpc::experimental::MessageAllocator< ::vlm::v1::GenerateRequest, ::vlm::v1::GenerateResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::vlm::v1::GenerateRequest, ::vlm::v1::GenerateResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Generate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Generate(::grpc::ServerContext* /*context*/, const ::vlm::v1::GenerateRequest* /*request*/, ::vlm::v1::GenerateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Generate(
      ::grpc::CallbackServerContext* /*context*/, const ::vlm::v1::GenerateRequest* /*request*/, ::vlm::v1::GenerateResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Generate(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::vlm::v1::GenerateRequest* /*request*/, ::vlm::v1::GenerateResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Health() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::vlm::v1::HealthRequest, ::vlm::v1::HealthResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::vlm::v1::HealthRequest* request, ::vlm::v1::HealthResponse* response) { return this->Health(context, request, response); }));}
    void SetMessageAllocatorFor_Health(
        ::grpc::experimental::MessageAllocator< ::vlm::v1::HealthRequest, ::vlm::v1::HealthResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::vlm::v1::HealthRequest, ::vlm::v1::HealthResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::vlm::v1::HealthRequest* /*request*/, ::vlm::v1::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Health(
      ::grpc::CallbackServerContext* /*context*/, const ::vlm::v1::HealthRequest* /*request*/, ::vlm::v1::HealthResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Health(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::vlm::v1::HealthRequest* /*request*/, ::vlm::v1::HealthResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_Generate<ExperimentalWithCallbackMethod_Health<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_Generate<ExperimentalWithCallbackMethod_Health<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Generate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Generate() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Generate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Generate(::grpc::ServerContext* /*context*/, const ::vlm::v1::GenerateRequest* /*request*/, ::vlm::v1::GenerateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Health() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::vlm::v1::HealthRequest* /*request*/, ::vlm::v1::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Generate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Generate() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Generate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Generate(::grpc::ServerContext* /*context*/, const ::vlm::v1::GenerateRequest* /*request*/, ::vlm::v1::GenerateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGenerate(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Health() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::vlm::v1::HealthRequest* /*request*/, ::vlm::v1::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHealth(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Generate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Generate() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Generate(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Generate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Generate(::grpc::ServerContext* /*context*/, const ::vlm::v1::GenerateRequest* /*request*/, ::vlm::v1::GenerateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Generate(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Generate(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Health() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Health(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::vlm::v1::HealthRequest* /*request*/, ::vlm::v1::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Health(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Health(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Generate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Generate() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::vlm::v1::GenerateRequest, ::vlm::v1::GenerateResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::vlm::v1::GenerateRequest, ::vlm::v1::GenerateResponse>* streamer) {
                       return this->StreamedGenerate(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Generate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Generate(::grpc::ServerContext* /*context*/, const ::vlm::v1::GenerateRequest* /*request*/, ::vlm::v1::GenerateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGenerate(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vlm::v1::GenerateRequest,::vlm::v1::GenerateResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Health() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::vlm::v1::HealthRequest, ::vlm::v1::HealthResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::vlm::v1::HealthRequest, ::vlm::v1::HealthResponse>* streamer) {
                       return this->StreamedHealth(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::vlm::v1::HealthRequest* /*request*/, ::vlm::v1::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedHealth(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vlm::v1::HealthRequest,::vlm::v1::HealthResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Generate<WithStreamedUnaryMethod_Health<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Generate<WithStreamedUnaryMethod_Health<Service > > StreamedService;
};

}  // namespace v1
}  // namespace vlm


#endif  // GRPC_vlm_2fv1_2fworker_2eproto__INCLUDED
